"""resume

Revision ID: a203fc995d20
Revises: 8deaae94c5f0
Create Date: 2021-05-20 13:13:39.180105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a203fc995d20'
down_revision = '8deaae94c5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_additional_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_me', sa.String(length=1000), nullable=True),
    sa.Column('key_skills', sa.String(length=500), nullable=True),
    sa.Column('knowledge_languages', sa.String(length=500), nullable=True),
    sa.Column('citizenship', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_additional_information_timestamp'), 'resume_additional_information', ['timestamp'], unique=False)
    op.create_table('resume_basic_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('date_of_birth', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('city_of_residence', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('link_social_network', sa.String(length=128), nullable=True),
    sa.Column('comment_link_social_network', sa.String(length=500), nullable=True),
    sa.Column('additional_link_social_network', sa.String(length=128), nullable=True),
    sa.Column('additional_comment_link_social_network', sa.String(length=500), nullable=True),
    sa.Column('desired_position', sa.String(length=128), nullable=True),
    sa.Column('comment_desired_position', sa.String(length=500), nullable=True),
    sa.Column('salary', sa.String(length=64), nullable=True),
    sa.Column('employment', sa.String(length=64), nullable=True),
    sa.Column('work_schedule', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_basic_information_timestamp'), 'resume_basic_information', ['timestamp'], unique=False)
    op.create_table('resume_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=128), nullable=True),
    sa.Column('educational_institution', sa.String(length=500), nullable=True),
    sa.Column('conducting_organization', sa.String(length=500), nullable=True),
    sa.Column('faculty', sa.String(length=500), nullable=True),
    sa.Column('specialization', sa.String(length=128), nullable=True),
    sa.Column('year_completion', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_education_timestamp'), 'resume_education', ['timestamp'], unique=False)
    op.create_table('resume_work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_working', sa.String(length=64), nullable=True),
    sa.Column('ending', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('company_field_activity', sa.String(length=128), nullable=True),
    sa.Column('post', sa.String(length=128), nullable=True),
    sa.Column('responsibilities_workplace', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_work_experience_timestamp'), 'resume_work_experience', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_work_experience_timestamp'), table_name='resume_work_experience')
    op.drop_table('resume_work_experience')
    op.drop_index(op.f('ix_resume_education_timestamp'), table_name='resume_education')
    op.drop_table('resume_education')
    op.drop_index(op.f('ix_resume_basic_information_timestamp'), table_name='resume_basic_information')
    op.drop_table('resume_basic_information')
    op.drop_index(op.f('ix_resume_additional_information_timestamp'), table_name='resume_additional_information')
    op.drop_table('resume_additional_information')
    # ### end Alembic commands ###
